dist: xenial

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8-dev"

addons:
  apt:
    packages:
    - gcc
    - libaio-dev
    - libblkid-dev
    - make

install:
    - pip install flake8

script:
    - make BUILDARGS="--build-lib=."
    - source tests/env.sh
    - pytest
    - flake8 --statistics tests python
